### PR TITLE
Update doc

### PR DESCRIPTION
**Pull request by xoac**
apply rustfmt on this lib
sync doc in src/lib.rs with information in README.md

### CODE REVIEW

**Comment by tailhook** [comment]
I'm okay with doc update. But any specific reason why you have applied rustfmt? Most (if not all) things aren't improvements here, some are harmful. To name a few:
1. Bytes in declaration of `buf` (`date.rs:32`) are aligned to have newlines at separators `T` and `.`
2. Loop comment in `date.rs:278` became in the wrong place
3. I like the contrast between `an = assignment` and `configuration="parameters"` (spaces around equals sign).

I understand rustfmt is a useful tradeoff for projects with high contribution traffic where it's easier to settle on rustfmt than to teach everyone good style. But this crate is prettly low-maintenance. And there is no need for such extra changes.

**Comment by xoac** [comment]
I used rustfmt because it's done im my IDE on save. So no general purpose.

I think I can come back to master, Add [skip attributes](https://github.com/rust-lang/rustfmt#tips) and  then do rustfmt and update doc. 

or just update doc. whatever you prefer

**Comment by tailhook** [comment]
Thanks, I prefer just updating docs.

**Comment by xoac** [comment]
Done

**Comment by tailhook** [comment]
Merged. Thanks!

**Pull request merged**
